import { createSlice } from "@reduxjs/toolkit";
import { URL } from "url";
const initialState = {
  bundles: {},
  currentBundleId: '',

};

export const onboardingSlice = createSlice({
  name: "fileProcessing",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    appendResults: (state: any, action: any) => {
      const { id, payload, type, source } = action.payload;
      if (!state.bundles[id]) state[id] = {};
      switch (type) {
        case 'progress':
          const { percent } = payload;
          state.bundles[id].conversionProgress = percent;
          return
        case 'result':
          let url =  URL.createObjectURL(new File([payload], ''));
          console.debug(url);
          state.bundles[id] = { ...state.bundles[id], payload: url, source };
          return;
        case 'queue':
          payload.forEach((p: any) => {
            state.bundles[p.id] = { ...state.bundles[p.id], ...p, source };
          });
          return
        default: return;
      }

    },
    QueueNextUpload: (state: any, action: any) => {

    },
    setTaskState: (state: any, action: any) => {

    },
    setProgress: (state: any, action: any) => {

    },
    setBundleId: (state: any, action: any) => {
      console.debug('set');
      state.currentBundleId = action.payload
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: () => {},
});

export const { appendResults, setTaskState, QueueNextUpload, setProgress, setBundleId,} = onboardingSlice.actions;

export default onboardingSlice.reducer;
