import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  results: {},
};

export const onboardingSlice = createSlice({
  name: "onboarding",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    appendResults: (state: any, action: any) => {
      const { id } = action.payload;
      if (!state.results[id]) state.results[id] = {};
      if (action.payload.type === "progress") {
        const {
          payload: { percent },
        } = action.payload;
        state.results[id].conversionProgress = percent;
      } else if (action.payload.type === "result") {
        state.results[id] = { ...state.results[id], ...action.payload };
      }
    },
    setFiles: (state: any, action: any) => {
      action.payload.forEach(f => {
        state.results[]
      })
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: () => {},
});

export const { appendResults } = onboardingSlice.actions;

export default onboardingSlice.reducer;
